# -*- coding: utf-8 -*-
"""hw4_carson_jenkins_ex_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l9hDy0Rn_7mW0wyGSJBsC-Q76_j-7y2t
"""

'''
Homework 4, Exercise 1
Carson Jenkins
03/09/23
This program includes classes for a Rectangle, Circle, 
and a Square. Each of these classes include methods 
that simulate area, diagonal, and the perimeter. 
'''

import math

class Rectangle:
  def __init__(self,length,width):
    self.length = length
    self.width = width
  def area(self):
    return self.length * self.width
  def diagonal(self):
    # diagonal calculated by taking the square root of the length squared plus the width squared
    return math.sqrt((self.length * self.length) + (self.width * self.width))
  def perimeter(self):
    return 2 * (self.length + self.width)

class Circle:
  def __init__(self,radius):
    self.radius = radius
  def area(self):
    # area calculated by pi multplied by radius squared
    return math.pi * (self.radius * self.radius)
  def diagonal(self):
    # this is the diameter
    return 2 * self.radius
  def perimeter(self):
    # permimeter calculated by 2pi multiplied by the radius
    return 2 * math.pi * self.radius

class Square:
  def __init__(self,side):
    self.side = side
  def area(self):
    return self.side * self.side
  def diagonal(self):
    # diagonal calculated by square root of 2 multiplied by the side
    return math.sqrt(2) * self.side
  def perimeter(self):
    return 4 * self.side

test = Circle((Rectangle(20, 10).diagonal())/2).perimeter()
print(test)