# -*- coding: utf-8 -*-
"""hw2_carson_jenkins_ex_4_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jR6zk9F6x4fDNDkBZweRl6pBT8iNARv5
"""

'''
Homework 2, Exercise 4 Part 3
Carson Jenkins
02/16/23
This program expands on the last, now implementing 
a random guesser instead of user input.
'''

import random
limit = 1000
lower = random.randint(1, limit)
upper = random.randint(lower, limit)
number = random.randint(lower, upper)
print("I am thinking of a number between {} and {}. You have 10 tries.".format(lower, upper))

counter = 0
autoPlayer = random.sample(range(lower, upper), 1)
while autoPlayer != number and counter <= 10:
  print("Take a guess.")
  autoPlayer = random.sample(range(lower, upper), 1)
  print(str(autoPlayer[0]))
  if autoPlayer[0] < number:
    print("Your guess is too low.")
  elif autoPlayer[0] > number:
    print("Your guess is too high.")
  counter += 1

if autoPlayer[0] == number:
  print("Good job! You guessed my number in {} guesses!".format(counter))
else:
  print("Sorry, the number I was thinking of was {}".format(number))