# -*- coding: utf-8 -*-
"""hw2_carson_jenkins_ex_4_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pj3QqBFFkHh8GqJTv4921rtjd_F5U_u0
"""

'''
Homework 2, Exercise 4 Part 1
Carson Jenkins
02/16/23
This program is a guess the number game. The user 
has 10 tries to guess the randomly generated number. 
'''

import random
number = random.randint(1,21)
print("I am thinking of a number between 1 and 20. You have 10 tries.")

counter = 0
inp = 0
while int(inp) != number and counter <= 10:
  print("Take a guess.")
  inp = input()
  if int(inp) < number:
    print("Your guess is too low.")
  elif int(inp) > number:
    print("Your guess is too high.")
  counter += 1

if int(inp) == number:
  print("Good job! You guessed my number in {} guesses!".format(counter))
else:
  print("Sorry, the number I was thinking of was {}".format(number))