# -*- coding: utf-8 -*-
"""hw2_carson_jenkins_ex_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CwaXD3ORYuy_25pK90-TJ1Ca75-F2aQA
"""

'''
Homework 2, Exercise 2
Carson Jenkins
02/16/23
This program expands on the last one, now with 
try and except statements to prevent passing a 
non-integer into the function.
'''

def collatz(number):
  try:
    if int(number)%2 == 0:
      value = int(number) // 2
      print(str(value))
      return value
    elif int(number)%2 == 1:
      value = 3 * int(number) + 1
      print(str(value))
      return value
  except:
    print("Enter an integer:")
    return 0
    
while collatz(input()) != 1:
  pass