# -*- coding: utf-8 -*-
"""hw2_carson_jenkins_ex_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1atqUIH4pbtW6q7_0lz2jeqIFF3vBtdnm
"""

'''
Homework 2, Exercise 1
Carson Jenkins
02/16/23
This program is a demonstration of the Collatz sequence.
Even numbers return number // 2, odd numbers return 3 * number + 1
The user keeps entering an integer until the function returns 1
'''

def collatz(number):
  if int(number)%2 == 0:
    value = int(number) // 2
    print(str(value))
    return value
  elif int(number)%2 == 1:
    value = 3 * int(number) + 1
    print(str(value))
    return value
  else:
    print("Error")
    return 0

while collatz(input()) != 1:
  print("Try again:")