# -*- coding: utf-8 -*-
"""hw2_carson_jenkins_ex_4_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X1FeMU789IO23LkuwrnxJsHuFtxv0ymG
"""

'''
Homework 2, Exercise 4 Part 2
Carson Jenkins
02/16/23
This program expands on the last, this time with random 
upper and lower bounds for the randomly generated number.
'''

import random
limit = 1000
lower = random.randint(1, limit)
upper = random.randint(lower, limit)
number = random.randint(lower, upper)
print("I am thinking of a number between {} and {}. You have 10 tries.".format(lower, upper))

counter = 0
inp = 0
while int(inp) != number and counter <= 10:
  print("Take a guess.")
  inp = input()
  if int(inp) < number:
    print("Your guess is too low.")
  elif int(inp) > number:
    print("Your guess is too high.")
  counter += 1

if int(inp) == number:
  print("Good job! You guessed my number in {} guesses!".format(counter))
else:
  print("Sorry, the number I was thinking of was {}".format(number))