# -*- coding: utf-8 -*-
"""hw2_carson_jenkins_ex_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hKOxFemN3TZbYHFVM3MxZmHkUUN2e-sh
"""

'''
Homework 2, Exercise 3
Carson Jenkins
02/16/23
This program runs through the various
functions that can be used on a list. 
'''

str_list = ["Wallet", "Phone", "Keys"]
print(str_list)

str_list.sort()
print(str_list)

print(str_list[0])

print(str_list[1:3])

print(str_list[-1])

print(str_list.index("Keys"))

str_list.append("Tablet")
print(str_list)

str_list.insert(1, "Mask")
print(str_list)

str_list.remove("Phone")
print(str_list)

str_list.reverse()
print(str_list)

def strList(input):
  value = ""
  for item in input[:-1]:
    value += item + ", "
  value += "and " + input[-1]
  return value
strList(str_list)