# -*- coding: utf-8 -*-
"""hw3_carson_jenkins_ex_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EG3C-aG_D467o1KuSBi4j6UBfz4w0yBv
"""

'''
Homework 3, Exercise 3
Carson Jenkins
02/23/23
This program emmulates an inventory in
a store that keeps track of items and 
allows you to remove and delete them.
'''

import pprint
def printInventory(inventory):
  pprint.pprint(inventory)

def addItem(inventory, item):
  if item in inventory:
    inventory[item] = inventory[item] + 1
  else:
    inventory[item] = 1
  return inventory

def deleteItem(inventory, item):
  if (item in inventory) and (inventory[item] > 0):
    inventory[item] = inventory[item] - 1
  else:
    print("Error, no items to delete")
  return inventory