# -*- coding: utf-8 -*-
"""hw3_carson_jenkins_ex_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hhS4CvZDZHgd1wE8OXRNRRpEA9r6qjLQ
"""

'''
Homework 3, Exercise 4
Carson Jenkins
02/23/23
Tic-Tac-Toe: fills data structure with user inputted X's and O's.
'''

board = [['', '', ''],
        ['', '', ''],
        ['', '', '']]

def printBoard(array):
  print()
  for i in range(len(array)):
    for j in range(len(array[0])):
      print(array[i][j] + " ", end='')
    print()

for i in range(len(board)):
  for j in range(len(board[0])):
    print("(" + str(i+1) + "," + str(j+1) + "): ")
    board[i][j] = input().upper()

printBoard(board)